# Generated by Django 4.2.30 on 2026-10-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_user_must_change_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="total_cents",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
