# Generated by Django 4.2.30 on 2026-10-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_receipt_total_cents"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[("requested", "Angefragt"), ("confirmed", "Bestätigt")],
                db_index=True,
                default="confirmed",
                max_length=10,
            ),
        ),
    ]
