# Generated by Django 4.2.30 on 2026-10-08 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_booking_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="summary",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="ErrorCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("front", models.TextField()),
                ("back", models.TextField()),
                ("note", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Offen"), ("mastered", "Gemeistert")],
                        db_index=True,
                        default="open",
                        max_length=10,
                    ),
                ),
                ("reviews", models.PositiveIntegerField(default=0)),
                ("last_result", models.CharField(blank=True, max_length=10)),
                ("last_reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("mastered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="error_cards",
                        to="core.booking",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="error_cards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tutor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authored_error_cards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
