# Generated by Django 4.2.30 on 2026-10-08 14:24

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_lesson_summary_error_cards"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="homework",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="homework_done",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="errorcard",
            name="kind",
            field=models.CharField(
                choices=[("error", "Fehler"), ("vocab", "Wortschatz")],
                db_index=True,
                default="error",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="lessonfile",
            name="content_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="lessonfile",
            name="data",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lessonfile",
            name="size",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="lessonfile",
            name="file",
            field=models.FileField(
                blank=True, upload_to=core.models.lesson_upload_path
            ),
        ),
        migrations.CreateModel(
            name="SessionFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("worksheet", "Arbeitsblatt"),
                            ("homework", "Hausaufgabe"),
                        ],
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("content_type", models.CharField(blank=True, max_length=100)),
                ("size", models.PositiveIntegerField(default=0)),
                ("data", models.BinaryField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="core.booking",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="session_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="SessionExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("link", models.URLField(blank=True, max_length=500)),
                ("done", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="core.booking",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
