# Generated by Django 4.2.30 on 2026-10-09 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_session_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="errorcard",
            name="page",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="errorcard",
            name="rects",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="errorcard",
            name="source_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="highlights",
                to="core.sessionfile",
            ),
        ),
    ]
