# Generated by Django 5.2.18 on 2026-10-09 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_curriculumtopic"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("sa", "Schularbeit"),
                            ("test", "Test"),
                            ("matura", "Matura"),
                            ("other", "Prüfung"),
                        ],
                        default="sa",
                        max_length=10,
                    ),
                ),
                ("date", models.DateField()),
                ("topic", models.CharField(blank=True, max_length=200)),
                ("grade", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("went_well", models.TextField(blank=True)),
                ("to_improve", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="school_tests_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="school_tests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["date", "created_at"],
            },
        ),
    ]
