# Generated by Django 5.2.18 on 2026-10-09 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_schooltest"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionfile",
            name="material",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="session_links",
                to="core.lessonfile",
            ),
        ),
        migrations.AlterField(
            model_name="sessionfile",
            name="data",
            field=models.BinaryField(null=True),
        ),
    ]
