# Generated by Django 5.2.18 on 2026-10-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_sessionfile_material"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar_bg",
            field=models.CharField(blank=True, default="", max_length=7),
        ),
        migrations.AddField(
            model_name="user",
            name="avatar_emoji",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
    ]
