from django.templatetags.static import static
from django.urls import path
from django.views.generic import RedirectView, TemplateView
from . import views

urlpatterns = [
    path('', views.landing_view, name='landing'),
    path('app/', views.app_view, name='app'),
    path('login/', views.login_view, name='login'),
    # Pure-content pages: legal notices required in Austria (Impressum §5 ECG,
    # Datenschutz GDPR Art. 13/14, AGB, Widerruf FAGG) and the FAQ.
    path('impressum/', TemplateView.as_view(template_name='impressum.html'), name='impressum'),
    path('datenschutz/', TemplateView.as_view(template_name='datenschutz.html'), name='datenschutz'),
    path('agb/', TemplateView.as_view(template_name='agb.html'), name='agb'),
    path('widerruf/', TemplateView.as_view(template_name='widerruf.html'), name='widerruf'),
    path('faq/', TemplateView.as_view(template_name='faq.html'), name='faq'),
    path('intro/', views.intro_view, name='intro'),
    path('cancel/<str:token>/', views.booking_cancel_view, name='booking_cancel'),
    # Tutor connects their Zoom/Teams account (OAuth redirect dance).
    path('oauth/video/<str:provider>/connect/', views.video_oauth_start, name='video_oauth_start'),
    path('oauth/video/<str:provider>/callback/', views.video_oauth_callback, name='video_oauth_callback'),
    # Public, token-guarded iCal subscription feed of a tutor's bookings.
    path('calendar/<str:token>.ics', views.calendar_feed, name='calendar_feed'),
    # Google Search fetches /favicon.ico from the site root, not the <link> tag.
    path('favicon.ico', RedirectView.as_view(url=static('favicon.ico'), permanent=True)),
    path('robots.txt', views.robots_txt, name='robots_txt'),
    path('sitemap.xml', views.sitemap_xml, name='sitemap_xml'),
    path('api/intro-bookings/', views.api_intro_booking),
    path('api/login/', views.api_login),
    path('api/logout/', views.api_logout),
    # Password lifecycle: forced first-login change, and the e-mailed
    # "Passwort vergessen" reset link (page + submit endpoint).
    path('api/password/change/', views.api_change_password),
    path('api/password/forgot/', views.api_password_forgot),
    path('api/password/reset/', views.api_password_reset),
    path('password/reset/<str:uidb64>/<str:token>/', views.password_reset_view, name='password_reset'),
    path('api/bookings/', views.api_bookings),
    path('api/bookings/<int:pk>/', views.api_booking_detail),
    path('api/bookings/<int:pk>/confirm/', views.api_booking_confirm),
    path('api/bookings/<int:pk>/decline/', views.api_booking_decline),
    path('api/error-cards/', views.api_error_cards),
    path('api/error-cards/<int:pk>/', views.api_error_card_detail),
    path('api/error-cards/<int:pk>/review/', views.api_error_card_review),
    path('api/bookings/<int:pk>/exercises/', views.api_session_exercises),
    path('api/exercises/<int:ex_id>/', views.api_session_exercise_detail),
    path('api/bookings/<int:pk>/files/', views.api_session_files),
    path('api/bookings/<int:pk>/files/import/', views.api_session_file_import),
    path('api/bookings/<int:pk>/pdf/', views.api_session_pdf),
    path('api/session-files/<int:file_id>/', views.api_session_file_detail),
    path('api/credits/<str:slug>/', views.api_credits),
    path('api/transactions/<int:txn_id>/cancel/', views.api_cancel_transaction),
    path('api/receipts/<str:number>/pdf/', views.api_receipt_pdf),
    path('api/checkout/', views.api_checkout),
    path('api/checkout/confirm/', views.api_checkout_confirm),
    path('api/stripe/webhook/', views.api_stripe_webhook),
    path('api/settle/', views.api_settle),
    path('api/students/<str:slug>/settle-link/', views.api_settle_link),
    path('api/students/<str:slug>/opening-credit/', views.api_opening_credit),
    path('settle/<str:token>/', views.settle_page, name='settle'),
    path('settle/<str:token>/checkout/', views.api_settle_token_checkout),
    path('api/users/me/billing/', views.api_billing),
    path('api/video-connection/', views.api_video_connection),
    path('api/calendar-link/', views.api_calendar_link),
    path('api/availability/', views.api_availability),
    path('api/custom-times/', views.api_custom_times),
    path('api/notes/<str:slug>/', views.api_notes),
    path('api/school-tests/', views.api_school_tests),
    path('api/school-tests/<int:pk>/', views.api_school_test_detail),
    path('api/lessons/<str:slug>/', views.api_lessons),
    path('api/topics/', views.api_topics),
    path('api/topics/<str:lesson_id>/', views.api_topic_detail),
    path('api/lesson-files/download/<int:file_id>/', views.api_lesson_file_download),
    path('api/lesson-files/<int:file_id>/', views.api_lesson_file_detail),
    path('api/lesson-files/<str:lesson_id>/', views.api_lesson_files),
    path('api/users/', views.api_users),
    path('api/users/<str:slug>/', views.api_user_detail),
    path('api/settings/', views.api_settings),
]
